#!/usr/bin/env python3

from json import loads

lista = loads(open("outfile.db").read())

print(lista)

for product in lista:
	print(product["Cantidad"] + " | " + product["Producto"] \  
	+ " |  " + product["Precio"])
